import = ["~/.cache/material/alacritty-dark.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 0.95

[window.padding]
x = 20
y = 0

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }
size = 15

[keyboard]
[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"

[[keyboard.bindings]]
key = "Q"
mods = "Control"
chars = "clear\u000d"

[[keyboard.bindings]]
key = "С"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "С"
mods = "Control"
chars = "\u0003"

[[keyboard.bindings]]
key = "М"
mods = "Control|Shift"
action = "Paste"
