theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
auto-info = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"

[keys.normal]
"C-s" = ":w"
"q" = ":q"
";" = "command_mode"
"C-c" = ":clipboard-yank"
"esc" = "collapse_selection"
"G" = "goto_file_end"
"A-j" = "move_line_down"
"A-k" = "move_line_up"
"x" = "delete_selection"
"X" = ["extend_line_up", "delete_selection"]
"C-w" = { "v" = "vsplit", "s" = "hsplit" }
"d" = { "d" = ["extend_to_line_bounds", "delete_selection"] }
"C-f" = ":run-shell-command zellij run --floating --close-on-exit -- sh -c 'source .venv/bin/activate && exec $SHELL'"
"K" = "hover"

[keys.normal.g]
"d" = "goto_definition"
"f" = "goto_reference"


[keys.normal.space]
"c" = { "a" = "code_action" }
"l" = { "r" = "rename_symbol" }
"e" = ":sh helix-wezterm.sh explorer"
"g" = ":run-shell-command zellij run --floating --close-on-exit -- lazygit"
"w" = ":run-shell-command zellij run --floating --close-on-exit -- rg"
"o" = ":open"
"a" = ":run-shell-command zellij run --floating --close-on-exit -- tree"
"t" = ":run-shell-command zellij run --floating --close-on-exit -- btm"
"v" = "vsplit"

[keys.normal.g.space]
"l" = ":run-shell-command zellij run --floating --close-on-exit -- gh pr list"
"r" = ":run-shell-command zellij run --floating --close-on-exit -- gh pr view"
"c" = ":run-shell-command zellij run --floating --close-on-exit -- gh pr comment"
"n" = ":run-shell-command zellij run --floating --close-on-exit -- gh pr create"
"m" = ":run-shell-command zellij run --floating --close-on-exit -- gh pr merge"

[keys.insert]
"j" = { "k" = "normal_mode" }
