line-length = 80
indent-width = 4
fix = true
unsafe-fixes = false
output-format = "pylint"
cache-dir = "~/.cache/ruff"

[format]
quote-style = "single"
line-ending = "auto"
indent-style = "tab"
docstring-code-format = true
docstring-code-line-length = 20

[lint]
select = ["ALL"]
ignore = ["B008"]

[lint.flake8-annotations]
mypy-init-return = true
