line-length = 88
indent-width = 4
fix = true
unsafe-fixes = true

[format]
quote-style = "single"
line-ending = "auto"
indent-style = "tab"
docstring-code-format = true
docstring-code-line-length = 20

[lint]
select = [
    "E",  
    "W",  
    "F",  
    "I",  
    "B",  
    "C4",  
    "UP", 
]

[lint.flake8-annotations]
mypy-init-return = true
